import type { Component, LogEntry } from './types';

export const mockComponents: Component[] = [
  {
    id: '1',
    name: '6ft Cedar Fence Panel',
    manufacturer: 'A1 Supplies',
    partNumber: 'A1-CFP-6',
    description: 'Standard 6-foot tall cedar privacy fence panel.',
    quantity: 120,
    location: 'Yard A, Bay 3',
    unitPrice: 75.5,
    datasheetUrl: '#',
    category: 'Fencing',
    lowStockThreshold: 20,
    lastOutwardDate: '2024-07-12T12:00:00.000Z',
  },
  {
    id: '2',
    name: '5in Black Gate Hinge (2-pack)',
    manufacturer: 'Hardy Hardware',
    partNumber: 'HH-BGH-5',
    description: 'Heavy-duty black steel hinges for gates.',
    quantity: 85,
    location: 'Warehouse, Shelf B4',
    unitPrice: 12.99,
    datasheetUrl: '#',
    category: 'Hardware',
    lowStockThreshold: 30,
    lastOutwardDate: '2024-07-17T12:00:00.000Z',
  },
  {
    id: '3',
    name: '80lb Bag of Concrete Mix',
    manufacturer: 'Quick-Set',
    partNumber: 'QS-CM-80',
    description: 'Fast-setting concrete mix for posts.',
    quantity: 250,
    location: 'Yard B, Pallet 12',
    unitPrice: 8.75,
    datasheetUrl: '#',
    category: 'Materials',
    lowStockThreshold: 100,
    lastOutwardDate: '2024-06-30T12:00:00.000Z',
  },
  {
    id: '4',
    name: '12ft Walk-Through Gate',
    manufacturer: 'A1 Gates',
    partNumber: 'A1-WTG-12',
    description: '12-foot wide single-swing walk-through gate, steel.',
    quantity: 8,
    location: 'Yard C, Section 2',
    unitPrice: 455.0,
    datasheetUrl: '#',
    category: 'Gates',
    lowStockThreshold: 5,
    lastOutwardDate: '2024-06-07T12:00:00.000Z',
  },
  {
    id: '5',
    name: 'Post Hole Digger',
    manufacturer: 'ToolTime',
    partNumber: 'TT-PHD-01',
    description: 'Manual post hole digger with fiberglass handles.',
    quantity: 12,
    location: 'Tool Shed',
    unitPrice: 45.0,
    datasheetUrl: '#',
    category: 'Tools',
    lowStockThreshold: 4,
    lastOutwardDate: '2024-07-07T12:00:00.000Z',
  },
  {
    id: '6',
    name: '4x4x8 Pressure-Treated Post',
    manufacturer: 'Lumber Inc.',
    partNumber: 'LI-PTP-448',
    description: '8-foot long pressure-treated 4x4 post.',
    quantity: 0,
    location: 'Yard A, Bay 5',
    unitPrice: 18.25,
    datasheetUrl: '#',
    category: 'Materials',
    lowStockThreshold: 50,
    lastOutwardDate: '2024-05-23T12:00:00.000Z',
  },
  {
    id: '7',
    name: 'Solar Post Cap Light (4-pack)',
    manufacturer: 'GlowRight',
    partNumber: 'GR-SPC-4PK',
    description: 'Solar-powered LED lights for 4x4 posts.',
    quantity: 40,
    location: 'Warehouse, Shelf C1',
    unitPrice: 29.99,
    datasheetUrl: '#',
    category: 'Hardware',
    lowStockThreshold: 15,
    lastOutwardDate: '2024-07-17T12:00:00.000Z',
  },
];


export const mockLogs: LogEntry[] = [
    {
      id: 'log1',
      user: { name: 'Admin User', avatar: 'https://placehold.co/40x40.png' },
      action: 'Added',
      componentName: '6ft Cedar Fence Panel',
      componentId: '1',
      timestamp: '2024-07-22T14:30:00.000Z',
      details: 'Added 50 units from new shipment.',
    },
    {
      id: 'log2',
      user: { name: 'Tech User', avatar: 'https://placehold.co/40x40.png' },
      action: 'Issued',
      componentName: '80lb Bag of Concrete Mix',
      componentId: '3',
      timestamp: '2024-07-22T11:05:00.000Z',
      details: 'Issued 20 bags for Johnson project.',
    },
     {
      id: 'log3',
      user: { name: 'Admin User', avatar: 'https://placehold.co/40x40.png' },
      action: 'Updated',
      componentName: '12ft Walk-Through Gate',
      componentId: '4',
      timestamp: '2024-07-21T09:15:00.000Z',
      details: 'Changed low stock threshold to 3.',
    },
    {
      id: 'log4',
      user: { name: 'Researcher User', avatar: 'https://placehold.co/40x40.png' },
      action: 'Removed',
      componentName: 'Post Hole Digger',
      componentId: '5',
      timestamp: '2024-07-20T16:45:00.000Z',
      details: 'Removed 1 broken unit.',
    },
    {
      id: 'log5',
      user: { name: 'Tech User', avatar: 'https://placehold.co/40x40.png' },
      action: 'Issued',
      componentName: '6ft Cedar Fence Panel',
      componentId: '1',
      timestamp: '2024-07-20T10:00:00.000Z',
      details: 'Issued 15 panels for Smith job.',
    },
];
