import type { Component } from './types';

export const mockComponents: Component[] = [
  {
    id: '1',
    name: 'STM32F401 Microcontroller',
    manufacturer: 'STMicroelectronics',
    partNumber: 'STM32F401RET6',
    description: 'ARM Cortex-M4 32-bit MCU, 84MHz, 512KB Flash',
    quantity: 42,
    location: 'A-01-C',
    unitPrice: 8.5,
    datasheetUrl: '#',
    category: 'ICs',
    lowStockThreshold: 10,
    lastOutwardDate: '2024-07-12T12:00:00.000Z',
  },
  {
    id: '2',
    name: '10k Ohm Resistor 0.25W',
    manufacturer: 'Vishay',
    partNumber: 'VSH-10K-025',
    description: 'Axial, 1% tolerance carbon film resistor.',
    quantity: 850,
    location: 'R-12-B',
    unitPrice: 0.05,
    datasheetUrl: '#',
    category: 'Resistors',
    lowStockThreshold: 200,
    lastOutwardDate: '2024-07-17T12:00:00.000Z',
  },
  {
    id: '3',
    name: '100nF Ceramic Capacitor',
    manufacturer: 'Murata',
    partNumber: 'MUR-100NF-50V',
    description: 'Multilayer ceramic capacitor, 50V, X7R',
    quantity: 8,
    location: 'C-05-A',
    unitPrice: 0.1,
    datasheetUrl: '#',
    category: 'Capacitors',
    lowStockThreshold: 100,
    lastOutwardDate: '2024-06-30T12:00:00.000Z',
  },
  {
    id: '4',
    name: 'Raspberry Pi 4 Model B 4GB',
    manufacturer: 'Raspberry Pi Foundation',
    partNumber: 'RPI4-4GB',
    description: 'Single-board computer with 4GB RAM',
    quantity: 15,
    location: 'DEV-01-A',
    unitPrice: 55.0,
    datasheetUrl: '#',
    category: 'Dev Boards',
    lowStockThreshold: 5,
    lastOutwardDate: '2024-06-07T12:00:00.000Z',
  },
  {
    id: '5',
    name: 'BMP280 Pressure Sensor',
    manufacturer: 'Bosch Sensortec',
    partNumber: 'BMP280',
    description: 'High-precision barometric pressure and temperature sensor.',
    quantity: 30,
    location: 'S-03-D',
    unitPrice: 2.5,
    datasheetUrl: '#',
    category: 'Sensors',
    lowStockThreshold: 10,
    lastOutwardDate: '2024-07-07T12:00:00.000Z',
  },
  {
    id: '6',
    name: 'Arduino Uno R3',
    manufacturer: 'Arduino',
    partNumber: 'A000066',
    description: 'ATmega328P based microcontroller board',
    quantity: 0,
    location: 'DEV-01-B',
    unitPrice: 23.0,
    datasheetUrl: '#',
    category: 'Dev Boards',
    lowStockThreshold: 5,
    lastOutwardDate: '2024-05-23T12:00:00.000Z',
  },
  {
    id: '7',
    name: '2N2222 NPN Transistor',
    manufacturer: 'Onsemi',
    partNumber: 'P2N2222AG',
    description: 'General purpose NPN transistor, TO-92 package.',
    quantity: 250,
    location: 'IC-08-F',
    unitPrice: 0.15,
    datasheetUrl: '#',
    category: 'ICs',
    lowStockThreshold: 50,
    lastOutwardDate: '2024-07-17T12:00:00.000Z',
  },
  {
    id: '8',
    name: '1N4001 Diode',
    manufacturer: 'Diodes Inc.',
    partNumber: '1N4001-T',
    description: '1A 50V general purpose rectifier diode.',
    quantity: 400,
    location: 'D-02-A',
    unitPrice: 0.08,
    datasheetUrl: '#',
    category: 'Other',
    lowStockThreshold: 100,
    lastOutwardDate: '2024-03-24T12:00:00.000Z',
  },
  {
    id: '9',
    name: 'LM7805 Voltage Regulator',
    manufacturer: 'Texas Instruments',
    partNumber: 'LM7805CT',
    description: '+5V fixed voltage regulator, TO-220 package.',
    quantity: 75,
    location: 'IC-02-C',
    unitPrice: 0.6,
    datasheetUrl: '#',
    category: 'ICs',
    lowStockThreshold: 20,
    lastOutwardDate: '2024-06-22T12:00:00.000Z',
  },
   {
    id: '10',
    name: 'Red LED 5mm',
    manufacturer: 'Kingbright',
    partNumber: 'KB-LED-R5',
    description: 'Standard 5mm Red LED, 20mA forward current',
    quantity: 1200,
    location: 'LED-01-R',
    unitPrice: 0.03,
    datasheetUrl: '#',
    category: 'Other',
    lowStockThreshold: 300,
    lastOutwardDate: '2024-07-20T12:00:00.000Z',
  },
];
